#! /bin/bash
# Provided by azure extension which comes from template parameters
# use free to determine min/max heap sizes / setting min and max to the same
MIN_HEAP_SIZE=`free | grep Mem | awk '{ printf(($2/1000000)*.20) }'`
MAX_HEAP_SIZE=`free | grep Mem | awk '{ printf($2/1000000) }'`
CLUSTER_NAME=$1
CLUSTER_PASSWORD=$2

# used by maven to pull the hazelcast binary
CLUSTER_VERSION=$3
export CLUSTER_VERSION
sh -c 'echo "CLUSTER_VERSION=$CLUSTER_VERSION" >> /etc/environment'
# set cluster version in pom file
sed -i -- 's/${env.CLUSTER_VERSION}/3.6.2/g' pom.xml

CLUSTER_SIZE=$4
CUSTOM_JAR=$5
SUBSCRIPTION_ID=$6

wget $CUSTOM_JAR
chmod +x install_hazelcast
chmod +x modify_configuration
#./modify_configuration --cluster-name=$CLUSTER_NAME --cluster-password=$CLUSTER_PASSWORD --cluster-version=$CLUSTER_VERSION --cluster-size=$CLUSTER_SIZE --subscription-id=$SUBSCRIPTION_ID --filename=hazelcast.xml
./modify_configuration --cluster-name=$CLUSTER_NAME --cluster-password=$CLUSTER_PASSWORD --cluster-version=$CLUSTER_VERSION --cluster-size=$CLUSTER_SIZE --filename=hazelcast.xml
./install_hazelcast $MIN_HEAP_SIZE $MAX_HEAP_SIZE $CLUSTER_VERSION
cp ./hazelcast-server.conf /etc/init/
service hazelcast-server start
