#! /bin/bash
# Provided by azure extension which comes from template parameters
# use free to determine min/max heap sizes / setting min and max to the same
MIN_HEAP_SIZE=`free | grep Mem | awk '{ printf(($2/1000000)*.20) }'`
MAX_HEAP_SIZE=`free | grep Mem | awk '{ printf($2/1000000) }'`
CLUSTER_NAME=$1
CLUSTER_PASSWORD=$2
CLUSTER_VERSION=$3
CLUSTER_SIZE=$4
SUBSCRIPTION_ID=$5
RESOURCE_GROUP=$6
chmod +x install_hazelcast
chmod +x modify_configuration
./modify_configuration --cluster-name=$CLUSTER_NAME --cluster-password=$CLUSTER_PASSWORD --cluster-version=$CLUSTER_VERSION --cluster-size=$CLUSTER_SIZE --subscription-id=$SUBSCRIPTION_ID --filename=hazelcast.xml
./install_hazelcast $MIN_HEAP_SIZE $MAX_HEAP_SIZE $CLUSTER_VERSION
sudo cp ./hazelcast-server.conf /etc/init/
sudo service hazelcast-server start
