#! /bin/bash
MIN_HEAP_SIZE=$1
MAX_HEAP_SIZE=$2
CLUSTER_VERSION=$3

sudo apt-get update -y
sudo apt-get install default-jdk -y
sudo apt-get install maven2 -y
sudo mvn install

#### version of hazelcast
if [ "x$CLUSTER_VERSION" = "x" ]
 then
   CLUSTER_VERSION="3.6.2"
fi

#### minimum heap size
if [ "x$MIN_HEAP_SIZE" = "x" ]
 then
   MIN_HEAP_SIZE=4G
fi
if [ "x$MAX_HEAP_SIZE" = "x" ]
 then
  MAX_HEAP_SIZE=4G
fi

if [ "x$MIN_HEAP_SIZE" != "x" ]; then
  JAVA_OPTS="$JAVA_OPTS -Xms${MIN_HEAP_SIZE}"
fi
if [ "x$MAX_HEAP_SIZE" != "x" ]; then
  JAVA_OPTS="$JAVA_OPTS -Xms${MAX_HEAP_SIZE}"
fi
# persist this variable to the VM environment
sudo sh -c 'echo "JAVA_OPTIONS=$JAVA_OPTS" >> /etc/environment'
sudo sh -c 'echo "CLUSTER_VERSION=$CLUSTER_VERSION" >> /etc/environment'

# create the hazelcast home directory
sudo mkdir /var/hazelcast
sudo cp pom.xml /var/hazelcast
sudo cp ./hazelcast.xml /var/hazelcast/
