#! /bin/bash

#assumes root/sudo user
apt-get update -y
apt-get install default-jdk -y
apt-get install maven2 -y
mvn install

# create the hazelcast home directory
mkdir /var/hazelcast
cp pom.xml /var/hazelcast
cp ./hazelcast.xml /var/hazelcast/
